import { ref } from "vue";
export const useBlogdetails = () => {
  const data = ref([
    {
      id: "1",
      link: "/blogs/Hahu_Muya_Public_Lecture_Series",
      images: "/hahujobnews/photo8.jpeg",
      to: "#news",
      category: "news",
      title: "HaHuJobs News",
      date: "21 june 2025",
      text: "HaHuMuya Public Lecture Series: Composition in Digital Art with AST. Proffessor Mezgebu Tesema",
    },

    {
      id: "2",
      link: "/blogs/Celebrating_Progress_The_STEEP_Project_Workshop",
      images: "/images/photo5.jpeg",
      to: "#news",
      category: "news",
      title: "HaHuJobs News",
      date: "5 june 2025",
      text: "Celebrating Progress: The STEEP Project Workshop",
    },
    {
      id: "3",
      link: "/blogs/A_Day_of_Empowerment_and_Exploration",
      images: "/images/photo5 (2).jpeg",
      to: "#news",
      category: "news",
      title: "HaHuJobs News",
      date: "24 May 2025",
      text: "STEM Career Fair at Dejazmach Wondyirad High School",
    },
    {
      id: "4",
      link: "/blogs/Hahu_Muya_Public_lecture_Series_Debut ",
      images: "/hahujobnews/photo5.jpeg",
      to: "#news",
      category: "news",
      title: "HaHuJobs News",
      date: "10 May 2025",
      text: "HahuMuya Public Lecture Series Debut: Araw, Inspiring Dive into Ethiopia's Tech Frontier",
    },
    {
      id: "5",
      link: "/blogs/Empowering_the_Next_Generation",
      images: "/hahujobnews/photo2.jpeg",
      to: "#news",
      category: "news",
      title: "HaHuJobs News",
      date: "2 May 2025",
      text: "Empowering the Next Generation: The Launch of the STEEP Champions Network",
    },
    {
      id: "6",
      link: "/blogs/steem_career_fair_at_kokebe_tsibah_high_school",
      images: "/hahujobnews/steep_kokebe_thumbinail_image.jpg",
      to: "#news",
      category: "news",
      title: "HaHuJobs News",
      date: "29 March 2025",
      text: "A Day of Inspiration and Discovery: STEM Career Fair at Kokebe Tsibah High School",
    },
    {
      id: "7",
      link: "/blogs/celebrating_international_women_day",
      images: "/hahujobnews/steep_women_day_thumbinail_image.png",
      to: "#news",
      category: "news",
      title: "HaHuJobs News",
      date: "8 March 2025",
      text: "Celebrating International Women's Day: A Day of Inspiration and Empowernment",
    },
    {
      id: "8",
      link: "/blogs/introducing_the_values_of_steep",
      images: "/hahujobnews/photo_1_2016.jpg",
      to: "#news",
      category: "news",
      title: "HaHuJobs News",
      date: "28 Feb 2025",
      text: "Introducing the Values of STEEP",
    },
    {
      id: "9",
      link: "/blogs/STEEP_Launching_Program_Ethiopia",
      images: "/hahujobnews/fifth_wlgrif.jpg",
      to: "#news",
      category: "news",
      title: "HaHuJobs News",
      date: "3 Nov 2024",
      text: "STEEP Launching Program in Ethiopia",
    },
    {
      id: "10",
      link: "/blogs/HaHuJobs_to_Partner_with_Humber_Polytechnic_to_Empower_Adolescent_Girls_in_Ethiopia",
      images: "/hahujobnews/hahu.webp",
      to: "#news",
      category: "news",
      title: "HaHuJobs News",
      date: "29 Oct 2024",
      text: "HaHuJobs to Partner with Humber Polytechnic to Empower Adolescent Girls in Ethiopia",
    },
    {
      id: "11",
      link: "/blogs/HaHuJobs_Addis_Ababa_Employment_Center_Launch",
      images: "/hahujobnews/hahujobs-employment-center-launch.png",
      to: "#news",
      category: "news",
      title: "HaHuJobs News",
      date: "7 December 2022",
      text: "HaHuJobs Addis Ababa Employment Center Launch",
    },
    {
      id: "12",
      link: "/blogs/HaHuJobs_concluded_a_three_month_training_program",
      images: "/hahujobnews/hahu_three_month_thumb.png",
      to: "#news",
      category: "news",
      title: "HaHuJobs News",
      date: "26 August 2022",
      text: "HaHuJobs concluded a three-month training program",
    },

    {
      id: "13",
      link: "/blogs/How_can_you_post_a_vacancy_on_HaHuJobs",
      images: "/guides/vacancy_post.png",
      to: "#guide",
      category: "guide",
      title: "Guides",
      date: "16 september 2022",
      text: "How Can You Post a Vacancy on HaHuJobs?",
    },

    {
      id: "14",
      link: "/blogs/Our_new_year's_gift_new_features_from_HaHuJobs",
      images: "/newfeatures/new_year_gift_thumbnail.png",
      to: "#new_features",
      category: "new_features",
      title: "New Features",
      date: "10 September 2022",
      text: "Our new years gift, new features from HaHuJobs",
    },

    {
      id: "15",
      link: "/blogs/KAS_SUR_PLACE_Scholarship_program_in_Ethiopia",
      images: "/scholarship/scholarship_1_mftyda.png",
      to: "#scholarship",
      category: "scholarship",
      title: "Scholarship",
      date: "10 September 2022",
      text: "KAS SUR_PLACE Scholarship Program In Ethiopia",
    },
    {
      id: "16",
      link: "/blogs/HaHuJobs_Online_Job_Application_Technical_Skill_Training",
      images: "/softskill/technical.png",
      to: "#soft_skill_training",
      category: "soft_skill_training",
      title: "Soft Skill Training",
      date: "3 January 2022",
      text: "HaHuJobs Online Job Application Technical Skill Training ",
    },

    {
      id: "17",
      link: "/blogs/MinabTech’s_Specialized_Software_Development_Training_for_Bahirdar_Institute_of_Technology",
      images: "/Technical/minab_bahirdar_training_1.png",
      to: "#technical_training",
      category: "technical_training",
      title: "Technical training",
      date: "11 April 2022",
      text: "MinabTech's Specialized Software Development Training for Bahirdar Institute of Technology",
    },
    {
      id: "18",
      link: "/blogs/Introducing_ALX_Africa",
      images: "/Technical/blog_post_4_i51xnl.jpg",
      to: "#technical_training",
      category: "technical_training",
      title: "Technical training",
      date: "20 February 2022",
      text: "Introducing ALX Africa",
    },
    {
      id: "19",
      link: "/blogs/Happy_Meskel_Festivities",
      images: "/wellwishes/meskel_festival.png",
      to: "#well_wishes",
      category: "well-wishes",
      title: "Well wishes",
      date: "26 September 2022",
      text: "Happy Meske Festivities",
    },
    {
      id: "20",
      link: "/blogs/Happy_Ethiopian_New_Year",
      images: "/wellwishes/hahu_new_year.png",
      to: "#well_wishes",
      category: "well_wishes",
      title: "Well wishes",
      date: "26 Septmeber 2022",
      text: "Happy Ethiopian New Year",
    },
    {
      id: "21",
      link: "/blogs/Hey_Let’s_Introduce_you_to_Awaqi",
      images: "/yout/awaqi_dedqr4.png",
      to: "#youth_platform",
      category: "youth_platform",
      title: "Youth PLatforms",
      date: "1 December 2021",
      text: "Hey! Let's Introduce you to Awaqi",
    },
  ]);
  return {
    blogdetails: data,
  };
};
